language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.2
  - 5.3

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PLUGIN_SLUG=$(basename $(pwd))
    - cd ..
    - mv $PLUGIN_SLUG "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"
    - cd "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover